spring:
  application:
    name: meetfootball
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meetfootball
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
springdoc:
  swagger-ui:
    path: /v1/api-docs/swagger